apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pytorch-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ludgerpaehler/argoflow/tree/v0.1.0
    targetRevision: test-deploy
    path: kubeflow/operators/pytorch
    kustomize:
      version: v4.0.5
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
