apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "a0UKkE2aGSw/9FydnLA4IvUS1MZnljNra4ZDkayao4J260/snQOp3iwSaZjPzf9Z\ntzTDIfWBzXP31Cjok7F+h7syoWvdYeEayFYw290fcv80PqHTa1I7uLPuywhjGziG\nlmwd2Wzm3VIYY1PYIp65l5KX6SvfPRQthYJlOG4iLWI="
